tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "awscli"
brew "cocoapods"
brew "direnv"
brew "mas"
brew "neovim"
brew "nmap"
brew "node"
brew "python@3.10"
brew "python@3.9"
brew "serverless"
brew "starship"
brew "stow"
cask "flutter"
cask "jetbrains-toolbox"
mas "Bitwarden", id: 1352778147
mas "TestFlight", id: 899247664
mas "Xcode", id: 497799835
