tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "awscli"
brew "cocoapods"
brew "colima"
brew "direnv"
brew "docker"
brew "hdf5"
brew "mas"
brew "neovim"
brew "nmap"
brew "node"
brew "python@3.10"
brew "python@3.9"
brew "serverless"
brew "starship"
brew "stow"
cask "adoptopenjdk8"
cask "flutter"
cask "google-chrome"
cask "jetbrains-toolbox"
mas "Apple Developer", id: 640199958
mas "TestFlight", id: 899247664
mas "Xcode", id: 497799835
